#!/bin/bash
###############################################
# install                                     #
#                                             #
#    This script, called by an EC2 instance   #
# at first launch, sets up the development    #
# environment.                                #
###############################################

set -x

# Change shell to zsh and install oh-my-zsh
chsh -s $(which zsh)
curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/zsh_install.sh
chmod u+x ~/zsh_install.sh
sh -c ~/zsh_install.sh && rm ~/zsh_install.sh
if [ -e ~/.zshrc.pre-oh-my-zsh ]; then
    cat ~/.zshrc.pre-oh-my-zsh >> ~/.zshrc
fi
cat >> ~/.zshrc <<-EOF
	set -o magicequalsubst
	if [ -f ~/.bash_aliases ]; then
	    . ~/.bash_aliases
	fi
	if [ -f ~/.profile ]; then
	   . ~/.profile
	fi
	export LC_CTYPE=en_US.UTF-8
EOF

# Copy over dotfiles from this repo
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cat ${DIR}/.gitconfig >> ~/.gitconfig
cat ${DIR}/.bash_aliases >> ~/.bash_aliases
cat ${DIR}/.tmux.conf >> ~/.tmux.conf
rsync -az ${DIR}/.ssh ~/

exit 0
